import { Theme, ThemeId } from '@/types/theme';

export const builtinThemes: Theme[] = [
  {
    id: 'builtin:white',
    name: '純潔白',
    preview: '#ffffff',
    colors: {
      '--bg': '#ffffff',
      '--bg2': '#f5f5f5',
      '--t1': '#000000',
      '--t2': '#262626',
      '--t3': '#666666',
      '--bd': '#e0e0e0',
      '--bd2': '#909090',
      '--card': '#ffffff',
      '--sh': '0 1px 3px rgba(0,0,0,.07),0 1px 2px rgba(0,0,0,.04)',
      '--primary': '#333333',
      '--primary-hover': '#111111',
      '--primary-text': '#ffffff',
      '--primary-text-hover': '#ffffff',
      '--primary-block': '#333333',
      '--danger': '#dc3545',
      '--success': '#28a745',
      '--warning': '#ffc107',
      '--btn-secondary': '#f5f5f5',
      '--btn-secondary-hover': '#e0e0e0',
      '--btn-secondary-text': '#000000',
      '--btn-secondary-text-hover': '#000000',
      '--btn-danger': '#dc3545',
      '--btn-danger-hover': '#b02a37',
      '--btn-danger-text': '#ffffff',
      '--btn-danger-text-hover': '#ffffff',
      '--btn-disabled': '#e0e0e0',
      '--btn-disabled-text': '#999999',
      '--link': '#333333',
      '--link-hover': '#111111',
      '--radius': '8px',
      '--font-sans': 'inherit',
      '--font-mono': 'inherit',
      '--transition': '0.2s ease',
    },
  },
  {
    id: 'builtin:gray',
    name: '極簡灰',
    preview: '#e8e8e8',
    colors: {
      '--bg': '#e8e8e8',
      '--bg2': '#d4d4d4',
      '--t1': '#111111',
      '--t2': '#333333',
      '--t3': '#595959',
      '--bd': '#b0b0b0',
      '--bd2': '#707070',
      '--card': '#f0f0f0',
      '--sh': '0 1px 3px rgba(0,0,0,.12),0 1px 2px rgba(0,0,0,.08)',
      '--primary': '#222222',
      '--primary-hover': '#000000',
      '--primary-text': '#ffffff',
      '--primary-text-hover': '#ffffff',
      '--primary-block': '#222222',
      '--danger': '#dc3545',
      '--success': '#28a745',
      '--warning': '#ffc107',
      '--btn-secondary': '#d4d4d4',
      '--btn-secondary-hover': '#b0b0b0',
      '--btn-secondary-text': '#111111',
      '--btn-secondary-text-hover': '#111111',
      '--btn-danger': '#dc3545',
      '--btn-danger-hover': '#b02a37',
      '--btn-danger-text': '#ffffff',
      '--btn-danger-text-hover': '#ffffff',
      '--btn-disabled': '#c0c0c0',
      '--btn-disabled-text': '#808080',
      '--link': '#222222',
      '--link-hover': '#000000',
      '--radius': '8px',
      '--font-sans': 'inherit',
      '--font-mono': 'inherit',
      '--transition': '0.2s ease',
    },
  },
  {
    id: 'builtin:dark',
    name: '深色夜',
    preview: '#1a1a2e',
    colors: {
      '--bg': '#1a1a2e',
      '--bg2': '#16213e',
      '--t1': '#e0e0e0',
      '--t2': '#a0a0b0',
      '--t3': '#707080',
      '--bd': '#2a2a3e',
      '--bd2': '#3a3a4e',
      '--card': '#232340',
      '--sh': '0 1px 3px rgba(0,0,0,.3)',
      '--primary': '#7c8cf0',
      '--primary-hover': '#5a6ad8',
      '--primary-text': '#1a1a2e',
      '--primary-text-hover': '#1a1a2e',
      '--primary-block': '#7c8cf0',
      '--danger': '#e74c5c',
      '--success': '#2ecc71',
      '--warning': '#f1c40f',
      '--btn-secondary': '#16213e',
      '--btn-secondary-hover': '#2a2a3e',
      '--btn-secondary-text': '#e0e0e0',
      '--btn-secondary-text-hover': '#e0e0e0',
      '--btn-danger': '#e74c5c',
      '--btn-danger-hover': '#c0392b',
      '--btn-danger-text': '#ffffff',
      '--btn-danger-text-hover': '#ffffff',
      '--btn-disabled': '#2a2a3e',
      '--btn-disabled-text': '#707080',
      '--link': '#7c8cf0',
      '--link-hover': '#5a6ad8',
      '--radius': '8px',
      '--font-sans': 'inherit',
      '--font-mono': 'inherit',
      '--transition': '0.2s ease',
    },
  },
  {
    id: 'builtin:ocean',
    name: '海洋藍',
    preview: '#f0f7fb',
    colors: {
      '--bg': '#f0f7fb',
      '--bg2': '#e3eef5',
      '--t1': '#1a2a3a',
      '--t2': '#3d5a6e',
      '--t3': '#6b8a9e',
      '--bd': '#b8d0dd',
      '--bd2': '#8aacbf',
      '--card': '#ffffff',
      '--sh': '0 1px 3px rgba(0,0,0,.08)',
      '--primary': '#2c6b9e',
      '--primary-hover': '#1d4f7a',
      '--primary-text': '#ffffff',
      '--primary-text-hover': '#ffffff',
      '--primary-block': '#2c6b9e',
      '--danger': '#dc3545',
      '--success': '#28a745',
      '--warning': '#ffc107',
      '--btn-secondary': '#e3eef5',
      '--btn-secondary-hover': '#b8d0dd',
      '--btn-secondary-text': '#1a2a3a',
      '--btn-secondary-text-hover': '#1a2a3a',
      '--btn-danger': '#dc3545',
      '--btn-danger-hover': '#b02a37',
      '--btn-danger-text': '#ffffff',
      '--btn-danger-text-hover': '#ffffff',
      '--btn-disabled': '#d8e0e8',
      '--btn-disabled-text': '#8aa0b0',
      '--link': '#2c6b9e',
      '--link-hover': '#1d4f7a',
      '--radius': '8px',
      '--font-sans': 'inherit',
      '--font-mono': 'inherit',
      '--transition': '0.2s ease',
    },
  },
  {
    id: 'builtin:forest',
    name: '森林綠',
    preview: '#f0f7f0',
    colors: {
      '--bg': '#f0f7f0',
      '--bg2': '#e0efe0',
      '--t1': '#1a2e1a',
      '--t2': '#3a5e3a',
      '--t3': '#6a8e6a',
      '--bd': '#b8d0b8',
      '--bd2': '#8aac8a',
      '--card': '#ffffff',
      '--sh': '0 1px 3px rgba(0,0,0,.08)',
      '--primary': '#3a8a3a',
      '--primary-hover': '#2a6e2a',
      '--primary-text': '#ffffff',
      '--primary-text-hover': '#ffffff',
      '--primary-block': '#3a8a3a',
      '--danger': '#dc3545',
      '--success': '#28a745',
      '--warning': '#ffc107',
      '--btn-secondary': '#e0efe0',
      '--btn-secondary-hover': '#b8d0b8',
      '--btn-secondary-text': '#1a2e1a',
      '--btn-secondary-text-hover': '#1a2e1a',
      '--btn-danger': '#dc3545',
      '--btn-danger-hover': '#b02a37',
      '--btn-danger-text': '#ffffff',
      '--btn-danger-text-hover': '#ffffff',
      '--btn-disabled': '#d8e0d8',
      '--btn-disabled-text': '#8aa08a',
      '--link': '#3a8a3a',
      '--link-hover': '#2a6e2a',
      '--radius': '8px',
      '--font-sans': 'inherit',
      '--font-mono': 'inherit',
      '--transition': '0.2s ease',
    },
  },
  {
    id: 'builtin:sepia',
    name: '懷舊棕',
    preview: '#faf0e0',
    colors: {
      '--bg': '#faf0e0',
      '--bg2': '#f0e6d0',
      '--t1': '#3a2a1a',
      '--t2': '#5a4a3a',
      '--t3': '#8a7a6a',
      '--bd': '#d8c8b0',
      '--bd2': '#b8a890',
      '--card': '#fff8f0',
      '--sh': '0 1px 3px rgba(0,0,0,.08)',
      '--primary': '#8a6a3a',
      '--primary-hover': '#6a4e2a',
      '--primary-text': '#ffffff',
      '--primary-text-hover': '#ffffff',
      '--primary-block': '#8a6a3a',
      '--danger': '#c0392b',
      '--success': '#27ae60',
      '--warning': '#e67e22',
      '--btn-secondary': '#f0e6d0',
      '--btn-secondary-hover': '#d8c8b0',
      '--btn-secondary-text': '#3a2a1a',
      '--btn-secondary-text-hover': '#3a2a1a',
      '--btn-danger': '#c0392b',
      '--btn-danger-hover': '#a93226',
      '--btn-danger-text': '#ffffff',
      '--btn-danger-text-hover': '#ffffff',
      '--btn-disabled': '#e8dcd0',
      '--btn-disabled-text': '#a09080',
      '--link': '#8a6a3a',
      '--link-hover': '#6a4e2a',
      '--radius': '8px',
      '--font-sans': 'inherit',
      '--font-mono': 'inherit',
      '--transition': '0.2s ease',
    },
  },
  {
    id: 'builtin:highcontrast',
    name: '高對比',
    preview: '#ffffff',
    colors: {
      '--bg': '#ffffff',
      '--bg2': '#f0f0f0',
      '--t1': '#000000',
      '--t2': '#000000',
      '--t3': '#333333',
      '--bd': '#000000',
      '--bd2': '#666666',
      '--card': '#ffffff',
      '--sh': 'none',
      '--primary': '#000000',
      '--primary-hover': '#333333',
      '--primary-text': '#ffffff',
      '--primary-text-hover': '#ffffff',
      '--primary-block': '#000000',
      '--danger': '#cc0000',
      '--success': '#006600',
      '--warning': '#cc6600',
      '--btn-secondary': '#f0f0f0',
      '--btn-secondary-hover': '#666666',
      '--btn-secondary-text': '#000000',
      '--btn-secondary-text-hover': '#ffffff',
      '--btn-danger': '#cc0000',
      '--btn-danger-hover': '#990000',
      '--btn-danger-text': '#ffffff',
      '--btn-danger-text-hover': '#ffffff',
      '--btn-disabled': '#cccccc',
      '--btn-disabled-text': '#666666',
      '--link': '#000000',
      '--link-hover': '#333333',
      '--radius': '4px',
      '--font-sans': 'inherit',
      '--font-mono': 'inherit',
      '--transition': '0s',
    },
  },
  {
    id: 'builtin:pastel',
    name: '粉彩',
    preview: '#fdf0f5',
    colors: {
      '--bg': '#fdf0f5',
      '--bg2': '#f9e6ee',
      '--t1': '#4a3a42',
      '--t2': '#7a6670',
      '--t3': '#aa96a0',
      '--bd': '#ecd8e0',
      '--bd2': '#d2bcc6',
      '--card': '#ffffff',
      '--sh': '0 1px 4px rgba(0,0,0,.06)',
      '--primary': '#e8a0a0',
      '--primary-hover': '#d08080',
      '--primary-text': '#4a3a42',
      '--primary-text-hover': '#4a3a42',
      '--primary-block': '#e8a0a0',
      '--danger': '#e88a8a',
      '--success': '#a0d0a0',
      '--warning': '#e8d080',
      '--btn-secondary': '#f9e6ee',
      '--btn-secondary-hover': '#ecd8e0',
      '--btn-secondary-text': '#4a3a42',
      '--btn-secondary-text-hover': '#4a3a42',
      '--btn-danger': '#e88a8a',
      '--btn-danger-hover': '#d07070',
      '--btn-danger-text': '#4a3a42',
      '--btn-danger-text-hover': '#4a3a42',
      '--btn-disabled': '#e8e0e4',
      '--btn-disabled-text': '#b0a0a6',
      '--link': '#e8a0a0',
      '--link-hover': '#d08080',
      '--radius': '12px',
      '--font-sans': 'inherit',
      '--font-mono': 'inherit',
      '--transition': '0.2s ease',
    },
  },
  {
    id: 'builtin:sunset',
    name: '夕陽橙',
    preview: '#fef5e7',
    colors: {
      '--bg': '#fef5e7',
      '--bg2': '#fde8cc',
      '--t1': '#3a2a1a',
      '--t2': '#6a5040',
      '--t3': '#9a8070',
      '--bd': '#e0c8a0',
      '--bd2': '#c0a878',
      '--card': '#fffbf5',
      '--sh': '0 1px 3px rgba(0,0,0,.08)',
      '--primary': '#d4760a',
      '--primary-hover': '#b35f08',
      '--primary-text': '#ffffff',
      '--primary-text-hover': '#ffffff',
      '--primary-block': '#d4760a',
      '--danger': '#c0392b',
      '--success': '#27ae60',
      '--warning': '#e67e22',
      '--btn-secondary': '#fde8cc',
      '--btn-secondary-hover': '#e0c8a0',
      '--btn-secondary-text': '#3a2a1a',
      '--btn-secondary-text-hover': '#3a2a1a',
      '--btn-danger': '#c0392b',
      '--btn-danger-hover': '#a93226',
      '--btn-danger-text': '#ffffff',
      '--btn-danger-text-hover': '#ffffff',
      '--btn-disabled': '#f0e0cc',
      '--btn-disabled-text': '#a09080',
      '--link': '#d4760a',
      '--link-hover': '#b35f08',
      '--radius': '8px',
      '--font-sans': 'inherit',
      '--font-mono': 'inherit',
      '--transition': '0.2s ease',
    },
  },
  {
    id: 'builtin:purple',
    name: '星空紫',
    preview: '#f5f0fa',
    colors: {
      '--bg': '#f5f0fa',
      '--bg2': '#ebe0f5',
      '--t1': '#2a1a3a',
      '--t2': '#5a4070',
      '--t3': '#8a70a0',
      '--bd': '#d0b8e0',
      '--bd2': '#b898c8',
      '--card': '#faf5ff',
      '--sh': '0 1px 3px rgba(0,0,0,.08)',
      '--primary': '#7c3aed',
      '--primary-hover': '#6d28d9',
      '--primary-text': '#ffffff',
      '--primary-text-hover': '#ffffff',
      '--primary-block': '#7c3aed',
      '--danger': '#dc3545',
      '--success': '#28a745',
      '--warning': '#ffc107',
      '--btn-secondary': '#ebe0f5',
      '--btn-secondary-hover': '#d0b8e0',
      '--btn-secondary-text': '#2a1a3a',
      '--btn-secondary-text-hover': '#2a1a3a',
      '--btn-danger': '#dc3545',
      '--btn-danger-hover': '#b02a37',
      '--btn-danger-text': '#ffffff',
      '--btn-danger-text-hover': '#ffffff',
      '--btn-disabled': '#e0d8e8',
      '--btn-disabled-text': '#9080a0',
      '--link': '#7c3aed',
      '--link-hover': '#6d28d9',
      '--radius': '8px',
      '--font-sans': 'inherit',
      '--font-mono': 'inherit',
      '--transition': '0.2s ease',
    },
  },
];

export function getThemeById(id: ThemeId | string): Theme | undefined {
  return builtinThemes.find((t) => t.id === id);
}

export const defaultTheme: Theme = builtinThemes[0]; // 純潔白
